version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./proofs:/app/proofs
    environment:
      - RUST_LOG=info
      - ZK_VERIFY_SEED_PHRASE=${ZK_VERIFY_SEED_PHRASE}
    restart: unless-stopped